user nginx;
worker_processes auto;

events {
    worker_connections 2048; # Handles 2048 connections per worker
    multi_accept on;
}

http {
    # Define the upstream block pointing to the app containers
    upstream nestjs_cluster {
        # Using Docker's internal DNS to resolve 'api' to all scaled instances
        server api:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://nestjs_cluster;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            
            # Forward real client IPs
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
